export const EMPENHO_REPOSITORY = 'EMPENHO_REPOSITORY';
export const FORNECEDOR_REPOSITORY = 'FORNECEDOR_REPOSITORY';
export const MOVIMENTACAO_TIPO_REPOSITORY = 'MOVIMENTACAO_TIPO_REPOSITORY';
export const MOVIMENTACAO_REPOSITORY = 'MOVIMENTACAO_REPOSITORY';